spring:
  application:
    api-prefix: /api/v1
    name: spring-boot-rest-api
  transaction:
    default-timeout: 300  # 5 phút (300 giây)
  mvc:
    async:
      request-timeout: 900000  # 15 phút (15*60*1000 ms)


payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: Z7MCGZGD
    secretKey: 28LF7UIUL9Z9K0DT8EWMWWCALOF08F63
    returnUrl: https://divineshopp.azurewebsites.net/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other

