spring:
  application:
    api-prefix: /api/v1
    name: spring-boot-rest-api
  transaction:
    default-timeout: 300
  mvc:
    async:
      request-timeout: 900000

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: Z7MCGZGD
    secretKey: 28LF7UIUL9Z9K0DT8EWMWWCALOF08F63
    returnUrl: http://localhost:8080/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other

