# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Divineshopp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://java5.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_10c9f57d60314f01ad5875f33369e59e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_37959fc660324086a1782227010d47ef }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: java5.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_10c9f57d60314f01ad5875f33369e59e }}/divineshopjava5:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Divineshopp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5c197a1d436040c0829ed307fa78cc13 }}
        images: 'java5.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_10c9f57d60314f01ad5875f33369e59e }}/divineshopjava5:${{ github.sha }}'